# Generated by Django 5.2.3 on 2025-07-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="message",
            name="signature",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
